package daae.learner.enums;

public enum AlgorithmType {
    CLASSIFICATION,
    REGRESSION,
    CLUSTERING,
    CLASSIFICATION_REGRESSION,
    CLASSIFICATION_CLUSTERING,
    REGRESSION_CLUSTERING

}
