version: "3"
services:
  learner-web:
    build: .
    ports:
      - 9002:8080
    command: sh ./deploy.sh
    volumes:
      - .:/app
      - $HOME/.m2:/root/.m2
    depends_on:
      - db
  db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dengue
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
